# Generated by Django 3.1.5 on 2021-02-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210215_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('date',)},
        ),
    ]
