# Generated by Django 3.1.5 on 2021-02-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210215_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='role',
            field=models.CharField(default='Designer', max_length=100),
        ),
    ]
