# Generated by Django 3.1.5 on 2021-02-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210215_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='role',
            field=models.CharField(default='Designer', max_length=100),
        ),
    ]
