# Generated by Django 3.1.5 on 2021-02-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210215_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='behance',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='dribble',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='linkedin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
