# Generated by Django 3.1.5 on 2021-02-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210215_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
