# Generated by Django 3.1.2 on 2021-02-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210217_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectTypes',
            new_name='ProjectType',
        ),
    ]
