# Generated by Django 3.1.2 on 2021-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210217_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
