# Generated by Django 3.1.2 on 2021-02-17 14:44

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20210217_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='intro',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
