# Generated by Django 3.1.6 on 2021-03-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_about_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='behance',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='dribble',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='instagram',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='role',
            field=models.CharField(default='Designer', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=10000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='years',
            field=models.CharField(max_length=1000),
        ),
    ]
